//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : PhoneLine.sm
//

#ifndef PHONELINE_SM_H
#define PHONELINE_SM_H


#define SMC_USES_IOSTREAMS

#include "statemap.h"

// Forward declarations.
class PhoneLineFSM;
class PhoneLineFSM_Idle;
class PhoneLineFSM_Conversation;
class PhoneLineFSM_Warning;
class PhoneLineFSM_Ready;
class PhoneLineFSM_Default;
class PhoneLineState;
class PhoneLineContext;
class PhoneLine;

class PhoneLineState :
    public statemap::State
{
public:

    PhoneLineState(const char * const name, const int stateId)
    : statemap::State(name, stateId)
    {};

    virtual void Entry(PhoneLineContext&) {};
    virtual void Exit(PhoneLineContext&) {};

    virtual void invalidNumber(PhoneLineContext& context);
    virtual void offHook(PhoneLineContext& context);
    virtual void onHook(PhoneLineContext& context);
    virtual void validNumber(PhoneLineContext& context);

protected:

    virtual void Default(PhoneLineContext& context);
};

class PhoneLineFSM
{
public:

    static PhoneLineFSM_Idle Idle;
    static PhoneLineFSM_Conversation Conversation;
    static PhoneLineFSM_Warning Warning;
    static PhoneLineFSM_Ready Ready;
};

class PhoneLineFSM_Default :
    public PhoneLineState
{
public:

    PhoneLineFSM_Default(const char * const name, const int stateId)
    : PhoneLineState(name, stateId)
    {};

};

class PhoneLineFSM_Idle :
    public PhoneLineFSM_Default
{
public:
    PhoneLineFSM_Idle(const char * const name, const int stateId)
    : PhoneLineFSM_Default(name, stateId)
    {};

    virtual void offHook(PhoneLineContext& context);
};

class PhoneLineFSM_Conversation :
    public PhoneLineFSM_Default
{
public:
    PhoneLineFSM_Conversation(const char * const name, const int stateId)
    : PhoneLineFSM_Default(name, stateId)
    {};

    virtual void invalidNumber(PhoneLineContext& context);
    virtual void onHook(PhoneLineContext& context);
    virtual void validNumber(PhoneLineContext& context);
};

class PhoneLineFSM_Warning :
    public PhoneLineFSM_Default
{
public:
    PhoneLineFSM_Warning(const char * const name, const int stateId)
    : PhoneLineFSM_Default(name, stateId)
    {};

    virtual void invalidNumber(PhoneLineContext& context);
    virtual void onHook(PhoneLineContext& context);
    virtual void validNumber(PhoneLineContext& context);
};

class PhoneLineFSM_Ready :
    public PhoneLineFSM_Default
{
public:
    PhoneLineFSM_Ready(const char * const name, const int stateId)
    : PhoneLineFSM_Default(name, stateId)
    {};

    virtual void Entry(PhoneLineContext&);
    virtual void Exit(PhoneLineContext&);
    virtual void invalidNumber(PhoneLineContext& context);
    virtual void onHook(PhoneLineContext& context);
    virtual void validNumber(PhoneLineContext& context);
};

class PhoneLineContext :
    public statemap::FSMContext
{
public:

    explicit PhoneLineContext(PhoneLine& owner)
    : FSMContext(PhoneLineFSM::Idle),
      _owner(owner)
    {};

    PhoneLineContext(PhoneLine& owner, const statemap::State& state)
    : FSMContext(state),
      _owner(owner)
    {};

    virtual void enterStartState()
    {
        getState().Entry(*this);
        return;
    }

    inline PhoneLine& getOwner()
    {
        return (_owner);
    };

    inline PhoneLineState& getState()
    {
        if (_state == NULL)
        {
            throw statemap::StateUndefinedException();
        }

        return dynamic_cast<PhoneLineState&>(*_state);
    };

    inline void invalidNumber()
    {
        getState().invalidNumber(*this);
    };

    inline void offHook()
    {
        getState().offHook(*this);
    };

    inline void onHook()
    {
        getState().onHook(*this);
    };

    inline void validNumber()
    {
        getState().validNumber(*this);
    };

private:
    PhoneLine& _owner;
};


#endif // PHONELINE_SM_H

//
// Local variables:
//  buffer-read-only: t
// End:
//
