//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : PhoneLine.sm
//

#include "PhoneLine.h"
#include "PhoneLine_sm.h"

using namespace statemap;

// Static class declarations.
PhoneLineFSM_Idle PhoneLineFSM::Idle("PhoneLineFSM::Idle", 0);
PhoneLineFSM_Conversation PhoneLineFSM::Conversation("PhoneLineFSM::Conversation", 1);
PhoneLineFSM_Warning PhoneLineFSM::Warning("PhoneLineFSM::Warning", 2);
PhoneLineFSM_Ready PhoneLineFSM::Ready("PhoneLineFSM::Ready", 3);

void PhoneLineState::invalidNumber(PhoneLineContext& context)
{
    Default(context);
}

void PhoneLineState::offHook(PhoneLineContext& context)
{
    Default(context);
}

void PhoneLineState::onHook(PhoneLineContext& context)
{
    Default(context);
}

void PhoneLineState::validNumber(PhoneLineContext& context)
{
    Default(context);
}

void PhoneLineState::Default(PhoneLineContext& context)
{
    throw (
        TransitionUndefinedException(
            (context.getState()).getName(),
            context.getTransition()));

}

void PhoneLineFSM_Idle::offHook(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.soundDialTone();
        context.setState(PhoneLineFSM::Ready);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Ready);
        throw;
    }
    context.getState().Entry(context);


}

void PhoneLineFSM_Conversation::invalidNumber(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.continues();
        context.setState(PhoneLineFSM::Conversation);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Conversation);
        throw;
    }
    context.getState().Entry(context);


}

void PhoneLineFSM_Conversation::onHook(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.disconnectedLine();
        context.setState(PhoneLineFSM::Idle);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Idle);
        throw;
    }
    context.getState().Entry(context);


}

void PhoneLineFSM_Conversation::validNumber(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.continues();
        context.setState(PhoneLineFSM::Conversation);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Conversation);
        throw;
    }
    context.getState().Entry(context);


}

void PhoneLineFSM_Warning::invalidNumber(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.slowBusyTone();
        context.setState(PhoneLineFSM::Warning);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Warning);
        throw;
    }
    context.getState().Entry(context);


}

void PhoneLineFSM_Warning::onHook(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.disconnectedLine();
        context.setState(PhoneLineFSM::Idle);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Idle);
        throw;
    }
    context.getState().Entry(context);


}

void PhoneLineFSM_Warning::validNumber(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.slowBusyTone();
        context.setState(PhoneLineFSM::Warning);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Warning);
        throw;
    }
    context.getState().Entry(context);


}

void PhoneLineFSM_Ready::Entry(PhoneLineContext& context)

{
    PhoneLine& ctxt = context.getOwner();

    ctxt.startTimer();
}

void PhoneLineFSM_Ready::Exit(PhoneLineContext& context)

{
    PhoneLine& ctxt = context.getOwner();

    ctxt.stopTimer();
}

void PhoneLineFSM_Ready::invalidNumber(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.PlayMessage();
        context.setState(PhoneLineFSM::Warning);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Warning);
        throw;
    }
    context.getState().Entry(context);


}

void PhoneLineFSM_Ready::onHook(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.disconnectedLine();
        context.setState(PhoneLineFSM::Idle);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Idle);
        throw;
    }
    context.getState().Entry(context);


}

void PhoneLineFSM_Ready::validNumber(PhoneLineContext& context)
{
    PhoneLine& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.findConnection();
        context.setState(PhoneLineFSM::Conversation);
    }
    catch (...)
    {
        context.setState(PhoneLineFSM::Conversation);
        throw;
    }
    context.getState().Entry(context);


}

//
// Local variables:
//  buffer-read-only: t
// End:
//
